//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> MealID { get; set; }
        public Nullable<int> DrinkID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> WaiterID { get; set; }
        public Nullable<bool> HasPayment { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> MealAmount { get; set; }
        public Nullable<int> DrinkAmount { get; set; }
    
        public virtual Drink Drink { get; set; }
        public virtual Meal Meal { get; set; }
        public virtual Table Table { get; set; }
        public virtual Waiter Waiter { get; set; }
    }
}
